apiVersion: v1
kind: ConfigMap
metadata:
  name: avro-schema-config
  namespace: connect
data:
  scada.json: |
    {
      "type": "record",
      "name": "SparkplugBPayload",
      "namespace": "com.example.sparkplug",
      "fields": [
        { "name": "timestamp", "type": "long" },
        { "name": "seq", "type": "int" },
        {
          "name": "metrics",
          "type": {
            "type": "array",
            "items": {
              "type": "record",
              "name": "Metric",
              "fields": [
                { "name": "name", "type": "string" },
                { "name": "alias", "type": ["null", "string"], "default": null },
                { "name": "timestamp", "type": "long" },
                { "name": "dataType", "type": "string" },
                { "name": "isHistorical", "type": ["null", "boolean"], "default": null },
                { "name": "isTransient", "type": ["null", "boolean"], "default": null },
                {
                  "name": "metaData",
                  "type": ["null", {
                    "type": "record",
                    "name": "MetaData",
                    "fields": [
                      { "name": "key", "type": "string" },
                      { "name": "value", "type": "string" }
                    ]
                  }],
                  "default": null
                },
                {
                  "name": "properties",
                  "type": {
                    "type": "record",
                    "name": "PropertySet",
                    "fields": [
                      {
                        "name": "propertyMap",
                        "type": {
                          "type": "map",
                          "values": "string"
                        },
                        "default": {}
                      }
                    ]
                  }
                },
                { "name": "value", "type": ["null", "string", "double", "int", "boolean"], "default": null },
                { "name": "isNull", "type": "boolean" }
              ]
            }
          }
        },
        { "name": "uuid", "type": ["null", "string"], "default": null },
        { "name": "body", "type": ["null", "bytes"], "default": null }
      ]
    }
