apiVersion: v1
kind: Service
metadata:
  name: jaycob-kafka-connect-service
  namespace: connect
spec:
  selector:
    app: jaycob-kafka-connect
  ports:
    - protocol: TCP
      name: one
      port: 8083
      targetPort: 8083
    - protocol: TCP
      name: two
      port: 7073
      targetPort: 7073
  type: NodePort
